### PR TITLE
Dependency > Covalent contract > Do not merge yet> add covalent indexer page

### PR DESCRIPTION
**Pull request by mnedelchev-vn**
@0xlucian @m4sterbunny @sukanyaparashar Hey guys, this a PR for new page inside the docs. It's under the Integrate section and it's about how to integrate Covalent. This is an indexer that provides historical on-chain data. Please have look and lmk if any issues. Thanks

### CODE REVIEW

**Review by m4sterbunny — COMMENTED** [review]
@mnedelchev-vn 
Step 2.2 
```2.2 Next, make a copy of `.env.local.example` file and rename it to `.env.local`. Place your Covalent API key there.```
differs to the instruction you have in the tutorial 
image

Pls align both according to best path

Pls also review my changes -- note change to step 3 (causing addition of step 4)

**Comment by m4sterbunny** [comment]
NB DEPENDENCY -- we need to sign contract with Covalent to support Covalent!!

**Comment by mnedelchev-vn** [comment]
> NB DEPENDENCY -- we need to sign contract with Covalent to support Covalent!!

@m4sterbunny ok, awaiting further notice about this. Just FYI we're supported by them, [check here.](https://www.covalenthq.com/docs/networks/)

**Comment by m4sterbunny** [comment]
@mnedelchev-vn remember the PR to fix the tutorials https://github.com/neonlabsorg/neon-tutorials/pull/16

**Comment by m4sterbunny** [comment]
FYI @mnedelchev-vn I added the link to the Covalent support page as part of my commit of updates to your page [check that here](https://github.com/neonlabsorg/neon-evm.docs/pull/101/commits/5603dff2761428f40287b14fcadf61ec10babaf1)

**Comment by mnedelchev-vn** [comment]
@m4sterbunny I'm fine with your updates on the covalent page, but I think you should bring back "View in Github" button in the page. We got this button also for other examples and it's just to help newbies with navigation to the project code. Screenshot:
Screenshot 2023-11-16 at 14 23 32

**Comment by m4sterbunny** [comment]
Tx @mnedelchev-vn -- I see from the grab that item was relocated above
image

**Comment by mnedelchev-vn** [comment]
@m4sterbunny missed that one, sorry!

**Pull request closed without merging**
