### PR TITLE
Add new ERC20ForSPL and ERC20ForSPLMintable standards.

### PR DESCRIPTION
**Pull request by sukanyaparashar**
This PR adds new doc pages for `ERC20ForSPL` and `ERC20ForSPLMintable` standards with explanation of the functions and the deployment scripts.

### CODE REVIEW

**Review by Vedad84 — CHANGES_REQUESTED** [review]
After reviewing the content of the pull request, I found one potential inconsistency:

In the file `docs/developing/standards/erc20forspl.md`, there is a typo in the description of the `transferSolana` function:

```
| transferSolana(bytes32 to, uint64 amount) -> bool                                                                                              |
| :--------------------------------------------------------------------------------------------------------------------------------------------- |
| This public function returns the boolean value for making transfers directly to Solana-like addresses. Balances are stored directly on Solana. |
```

The word "instuction" should be "instruction":

```
This public function returns the boolean value for making transfers directly to Solana-like addresses. Balances are stored directly on Solana.
```

Apart from this typo, I did not notice any other inconsistencies in the content provided.

@sukanyaparashar please correct the typo and resubmit.  Thanks.

**Comment by sukanyaparashar** [comment]
> After reviewing the content of the pull request, I found one potential inconsistency:
> 
> In the file `docs/developing/standards/erc20forspl.md`, there is a typo in the description of the `transferSolana` function:
> 
> ```
> | transferSolana(bytes32 to, uint64 amount) -> bool                                                                                              |
> | :--------------------------------------------------------------------------------------------------------------------------------------------- |
> | This public function returns the boolean value for making transfers directly to Solana-like addresses. Balances are stored directly on Solana. |
> ```
> 
> The word "instuction" should be "instruction":
> 
> ```
> This public function returns the boolean value for making transfers directly to Solana-like addresses. Balances are stored directly on Solana.
> ```
> 
> Apart from this typo, I did not notice any other inconsistencies in the content provided.
> 
> @sukanyaparashar please correct the typo and resubmit. Thanks.

Thanks for the review, @Vedad84 ! I have fixed the typo here https://github.com/neonlabsorg/neon-evm.docs/blob/745b3cf27bc89f773ddb8f2161d6228b2b19106d/docs/developing/standards/erc20forspl.md?plain=1#L117.

I have marked this PR as a draft for now because I am waiting to add the factory contract addresses to this page. I will let you know again once its ready to merge and approved by @mnedelchev-vn and @0xlucian.

**Review by mnedelchev-vn — APPROVED** [review]

**Comment by Vedad84** [comment]
@sukanyaparashar , can I just check that the following is intended and not a typo:

_Inconsistent Factory Contract Addresses on Devnet:_

In the erc20forspl.md file, the Devnet ERC20ForSPL Factory Contract address is updated to 0x238Ea562E1fb314e2c6bbaA58E0F1B3B4154c1f6.

However, in the erc20forspl_mintable.md file, the Devnet ERC20ForSPLMintable Factory Contract address is updated to 0x30Ae1963DDf63e7406235dBcD557d9222FB010Cc.

Can I just check that the Factory Contract addresses for the same network (Devnet) are consistent across both files. If these are intended to be different contracts, it would be helpful to clarify the distinction between them in the documentation.

**Comment by sukanyaparashar** [comment]
Closing this PR and have opened a new one https://github.com/neonlabsorg/neon-evm.docs/pull/170 against the `develop` branch.

**Pull request closed without merging**
