### PR TITLE
Replace the old pull service Pyth integration example with the new pusher service example of reading Pyth Solana price feeds

### PR DESCRIPTION
**Pull request by sukanyaparashar**
This PR adds the new example repository for Pyth integration with reading Pyth Solana price feeds natively and also updates the price feeds link.

### CODE REVIEW

**Review by mnedelchev-vn — APPROVED** [review]

**Comment by mnedelchev-vn** [comment]
@sukanyaparashar please review [the PR with pyth's example changes](https://github.com/neonlabsorg/neon-tutorials/pull/35) and then let's update the code in this docs example.

**Review by mnedelchev-vn — APPROVED** [review]
lgtm

**Review by Vedad84 — CHANGES_REQUESTED** [review]
After reviewing the content of the GitHub pull request, I noticed a few inconsistencies:

1. The title mentions "Update Pyth integration with the new example", but the file changes seem to be replacing the old example with a new one, rather than updating an existing integration.

2. The first few lines under the "TL;DR" section provide contradictory information. One line says "First call `pyth.updatePriceFeeds`", and the next line says "Next call `pyth.getPrice`", which implies that calling `getPrice` should come before `updatePriceFeeds`.

3. The "Boilerplate contract" section is empty, despite the heading suggesting that it should contain some boilerplate contract code or information.

4. The section "How to integrate with the Pyth contract" is duplicated, and the second instance is empty.

5. The section "Considerations for using Pyth on Neon EVM" mentions that the example is based on a specific repository, but the link to the repository is missing.

6. The "Step 2: Set Up MetaMask Accounts" section contains an image with a broken path (`mm_p_key` is not a valid image path).

7. The "What next?" section is immediately followed by another "Step 3: Compile Contracts" section, which seems out of place.

8. The "How to Deploy to Neon EVM" section is commented out, which is inconsistent with the surrounding content.

These inconsistencies might cause confusion for developers trying to follow the instructions or understand the integration process. It would be beneficial to review and address these issues to ensure a clear and consistent documentation.

If any of these inconsistencies should be the way they currently are than feel free to provide the relevant comment and I will merge the PR in that case.

**Comment by sukanyaparashar** [comment]
> After reviewing the content of the GitHub pull request, I noticed a few inconsistencies:
> 
> 1. The title mentions "Update Pyth integration with the new example", but the file changes seem to be replacing the old example with a new one, rather than updating an existing integration.
> 2. The first few lines under the "TL;DR" section provide contradictory information. One line says "First call `pyth.updatePriceFeeds`", and the next line says "Next call `pyth.getPrice`", which implies that calling `getPrice` should come before `updatePriceFeeds`.
> 3. The "Boilerplate contract" section is empty, despite the heading suggesting that it should contain some boilerplate contract code or information.
> 4. The section "How to integrate with the Pyth contract" is duplicated, and the second instance is empty.
> 5. The section "Considerations for using Pyth on Neon EVM" mentions that the example is based on a specific repository, but the link to the repository is missing.
> 6. The "Step 2: Set Up MetaMask Accounts" section contains an image with a broken path (`mm_p_key` is not a valid image path).
> 7. The "What next?" section is immediately followed by another "Step 3: Compile Contracts" section, which seems out of place.
> 8. The "How to Deploy to Neon EVM" section is commented out, which is inconsistent with the surrounding content.
> 
> These inconsistencies might cause confusion for developers trying to follow the instructions or understand the integration process. It would be beneficial to review and address these issues to ensure a clear and consistent documentation.
> 
> If any of these inconsistencies should be the way they currently are than feel free to provide the relevant comment and I will merge the PR in that case.



> After reviewing the content of the GitHub pull request, I noticed a few inconsistencies:
> 
> 1. The title mentions "Update Pyth integration with the new example", but the file changes seem to be replacing the old example with a new one, rather than updating an existing integration.
> 2. The first few lines under the "TL;DR" section provide contradictory information. One line says "First call `pyth.updatePriceFeeds`", and the next line says "Next call `pyth.getPrice`", which implies that calling `getPrice` should come before `updatePriceFeeds`.
> 3. The "Boilerplate contract" section is empty, despite the heading suggesting that it should contain some boilerplate contract code or information.
> 4. The section "How to integrate with the Pyth contract" is duplicated, and the second instance is empty.
> 5. The section "Considerations for using Pyth on Neon EVM" mentions that the example is based on a specific repository, but the link to the repository is missing.
> 6. The "Step 2: Set Up MetaMask Accounts" section contains an image with a broken path (`mm_p_key` is not a valid image path).
> 7. The "What next?" section is immediately followed by another "Step 3: Compile Contracts" section, which seems out of place.
> 8. The "How to Deploy to Neon EVM" section is commented out, which is inconsistent with the surrounding content.
> 
> These inconsistencies might cause confusion for developers trying to follow the instructions or understand the integration process. It would be beneficial to review and address these issues to ensure a clear and consistent documentation.
> 
> If any of these inconsistencies should be the way they currently are than feel free to provide the relevant comment and I will merge the PR in that case.

@Vedad84 Thanks for the comments. This page has been completely refactored because the way this page was written for Pyth price feeds isn't required now. Previously the Pyth price feeds were used from Pyth network as pull service. But now we have found out that we can natively read Solana price feeds which is a push service and the users doesn't have to update the price before reading it from the Pyth network.

1. Yes, actually we are replacing the whole example with a new one for reading Pyth price feeds. I have updated the heading of this PR to "Replacing the Pyth integration example with a new one".

For all the next points you have mentioned, the inconsistencies are meant to be like this because this is a complete different way of Pyth integration. If you want to check all the details and the links that are mentioned in this document, then you can locally run it in your machine with the following steps and verify if everything works as expected.

* Clone the main repository - `git clone https://github.com/neonlabsorg/neon-evm.docs.git`
* Install the dependencies - `yarn install` (You need to have yarn installed on your machine)
* Checkout to this PR - `gh pr checkout 143`
* Start the local instance - `yarn start`

This will run a local instance of the website on port 3000 and you would be able to verify the whole PR.

Let me know if you have any other queries or need any help to run the local instance.

**Pull request merged**
