### PR TITLE
Add WHALE token to the Mainnet token list

### PR DESCRIPTION
**Pull request by sukanyaparashar**
This PR adds the **WHALE** token to the ERC-20 token list for Mainnet. This data is taken from https://github.com/neonlabsorg/token-list/blob/055531c62a9e5779df8a00e174a4c0bf033231ae/tokenlist.json#L530.

### CODE REVIEW

**Review by Vedad84 — CHANGES_REQUESTED** [review]
"transfering" should be "transferring"

File: ./docs/composability/using_composability/transfer_spl_token.md
Line: 381
Context: Description of token transfer process

**Comment by sukanyaparashar** [comment]
> "transfering" should be "transferring"
> 
> File: ./docs/composability/using_composability/transfer_spl_token.md Line: 381 Context: Description of token transfer process

@Vedad84 Thanks for pointing this out. This PR is not related to the composability docs. Will it be okay if I change/update this typo error when I push new PR for the Composability feature? Let me know, or otherwise I will change it in this PR itself.

**Comment by oable** [comment]
@sukanyaparashar please create PR to the develop branch before merging it to main branch.

**Comment by sukanyaparashar** [comment]
> @sukanyaparashar please create PR to the develop branch before merging it to main branch.

@oable ! Sure, I will create a PR to the develop branch now.

**Comment by Vedad84** [comment]
Hey @sukanyaparashar ,

If you are creating the PR to align with 'develop' branch, please try to fix it in that instance if not too late.
Otherwise, leave it for the next PR.

Thanks.

**Comment by sukanyaparashar** [comment]
Closing this one because a new PR has been created against the "develop" branch.

**Pull request closed without merging**
