### PR TITLE
feat: add flair indexing

### PR DESCRIPTION
**Pull request by kasrakhosravi**
Screenshot 2023-09-22 at 13 38 26

### CODE REVIEW

**Comment by mnedelchev-vn** [comment]
Hi @kasrakhosravi , I've took the time to follow the steps in the provided doc page about Flair integration and I'm stuck at generating the **manifest.yml** file. These are the steps that I've followed:

1. git clone https://github.com/flair-sdk/starter-boilerplate.git
2. pnmp i
3. cp config.prod.json config.json
4. pnpm generate-and-deploy _( here the script returned following error - 🔴 deployment failed (400 error response): "Client does not have access to namespace boilerplate-prod" )_
5. pnpm flair backfill --chain 245022934 --address 0xEA6B04272f9f62F997F666F07D3a974134f7FFb9 -d backward --max-blocks 10000 
_Here the script returned following error:_
   _›   Error: 🔴 backfill job creation failed: No indexer found for chain "245022934", please add relevant config in manifest.yml (cn: 8156, cid: 
   ›   cln-20b057c6-11f0-43c2-bdff-8872a9be5d65)
   ›   Code: BACKFILL_JOB_CREATION_FAILED_

This is the content of my **config.prod.json** file:
{
  "cluster": "prod",
  "namespace": "boilerplate-prod",
  "indexers": [
    {
        "chainId": 245022934,
        "enabled": true,
        "ingestionFilterGroup": "default",
        "processingFilterGroup": "default",
        "sources": [
          "https://neon-mainnet.everstake.one"
        ]
      }
  ]
}

My test API key is **akprd-3ec7b058-734f-43ea-9aac-03fbad762262** . Can you collaborate?

**Comment by kasrakhosravi** [comment]
hey @mnedelchev-vn. thanks for looking into this

can you change the namespace in the config to a unique one (e.g neon-indexing-test)? 

the `boilerplate-prod` namespace is already deployed under another account. after this successful deployment, the backfill should work also

**Comment by mnedelchev-vn** [comment]
@kasrakhosravi After changing the namespace to unique one I was able to query past data from Neon EVM network. I will let my team know of the result, thank you!

**Comment by m4sterbunny** [comment]
@mnedelchev-vn have you updated the page to add the clarification that you need?

**Comment by mnedelchev-vn** [comment]
@m4sterbunny no I haven't. If we will be accepting the Flair integration in our docs then let's accept this PR and then make a separate PR to add this notice that you've to use new unique namespace. The PR made by Flair's team is from another repo, not from a branch in our repo.

**Pull request merged**
